name: nav_view
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_staggered_grid_view: ^0.4.0
  measured_size: ^1.0.0
  equatable: ^2.0.3
  cached_network_image: ^3.0.0
  firebase_storage: ^8.0.4
  image_cropper: ^1.4.0
  image_picker: 
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

  flutter_native_splash: ^1.2.0
  

flutter_native_splash:
  color: "#0063dd"
  image: assets/logo.png #u must place logo.png in your assets folder
  android: true
  ios: true



flutter:
  uses-material-design: true
  assets:
  - assets/


